  name: dev
  channels:
    - conda-forge
    - defaults
  dependencies:
    - python=3.8
    - pip
    - ipython
    - jupyter
    - jupyterlab>=3
    - scikit-learn
    - pip:
      - pymetager
      - pandas-profiling[notebook]
      