  name: dev
  channels:
    - conda-forge
    - defaults
  dependencies:
    - python=3.8
    - pip
    - ipython
    - jupyter
    - jupyterlab>=3
    - pandas-profiling
    - scikit-learn
    - plotly::plotly
    - seaborn
    - pip:
      - pymetager